services:
  endpoint:
    image: node:18
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: academic-tasks-endpoint
    restart: always
    working_dir: /code/services/service-endpoint
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/code/services/service-endpoint
      - ../../packages:/code/packages
    networks:
      - academic-tasks-net

networks:
  academic-tasks-net:
    external: true