services:
  server:
    image: node:18
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: academic-tasks-server
    working_dir: /code
    depends_on:
      - server-db
      - server-meilisearch
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/code
    networks:
      - academic-tasks-net

  server-db:
    image: postgres:15-alpine
    container_name: academic-tasks-db
    volumes:
      - 'academic-tasks-db-data:/var/lib/postgresql/data'
      - './volumes/db/initdb.d:/docker-entrypoint-initdb.d'
    env_file:
      - .db.env
    networks:
      - academic-tasks-net
    ports:
      - 5432:5432

  server-meilisearch:
    image: getmeili/meilisearch:v1.0.2
    container_name: academic-tasks-meilisearch
    ports:
      - 7700:7700
    env_file:
      - .meilisearch.env
    volumes:
      - 'academic-tasks-meilisearch-data:/meili_data'
    networks:
      - academic-tasks-net

  sso:
    build:
      context: ./devops/docker/sso/image
      args:
        - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.scripts=enabled
    entrypoint: /opt/keycloak/bin/kc.sh
    command: start-dev --import-realm
    container_name: academic-tasks-sso
    env_file:
      - .kc.env
    depends_on:
      - server-db
    networks:
      - academic-tasks-net

networks:
  academic-tasks-net:
    external: true

volumes:
  academic-tasks-db-data:
  academic-tasks-meilisearch-data:
