export * from "./cargo";
export * from "./curso";
export * from "./disciplina";
export * from "./lista";
export * from "./permissao";
export * from "./professor";
export * from "./tarefa";
export * from "./turma";
export * from "./usuario";
